# Generated by Django 3.2.7 on 2021-09-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight1', models.DecimalField(decimal_places=3, max_digits=6)),
                ('weight2', models.DecimalField(decimal_places=3, max_digits=6)),
                ('netWeight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('vehicleNumber', models.CharField(max_length=20)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('vehicleType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicals', to='main.vehicletype')),
            ],
        ),
    ]
