# Generated by Django 3.2.7 on 2021-09-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210911_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
    ]
