# Generated by Django 3.2.7 on 2021-09-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_reading_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='netWeight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reading',
            name='weight1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reading',
            name='weight2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10),
        ),
    ]
