# Generated by Django 3.2.7 on 2021-09-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210911_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='netWeight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
